services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      target: ${STAGE}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DUMMY_ENV_1: ${DUMMY_ENV_1}
      DUMMY_ENV_2: ${DUMMY_ENV_2}